set(requires esp-dl)
idf_build_get_property(component_targets __COMPONENT_TARGETS)
if ("___idf_espressif__esp-dl" IN_LIST component_targets)
    idf_component_get_property(espdl_dir espressif__esp-dl COMPONENT_DIR)
elseif ("___idf_esp-dl" IN_LIST component_targets)
    idf_component_get_property(espdl_dir esp-dl COMPONENT_DIR)
else()
    message(FATAL_ERROR "ESP-DL component not found")
endif()
include(${espdl_dir}/fbs_loader/cmake/utilities.cmake)
idf_component_register(SRCS "app_main.cpp" REQUIRES ${requires})
target_add_aligned_binary_data(${COMPONENT_LIB} "models/s3/model.espdl" BINARY)
